spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anor
    username: postgres
    password: yusufbek200
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true

telegram:
  webhook-path: "https://a8ae-82-215-93-201.in.ngrok.io"
  bot-name: "@new_anor_bot"
  bot-token: "5398597750:AAFppiXc3rfrsS8ASIBakenbeNNTdhXTe7Y"